# Generated by Django 4.0.3 on 2023-08-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='autor',
            new_name='author',
        ),
    ]
